version: '3'
services:

    minginx_service:
        container_name: apache
        ports: 
            - 0.0.0.0:8080:80 # Estos son los puertos que mapeo
        image: httpd
        volumes:
            - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
            - ./logs:/logs
    filebeat_service:
        container_name: filebeat
        image: docker.elastic.co/beats/filebeat:7.8.0
        volumes: 
          - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yaml
          - ./logs:/logs
    logstash_service:
        container_name: logstash
        image: docker.elastic.co/logstash/logstash:7.8.0 
        volumes: 
            - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
        environment: 
            MONITORING_ENABLED: 'false'
        restart: always
        